app:
    resource: "@AppBundle/Controller/"
    type:     annotation
home:
    path: /home
    defaults: { _controller: AppBundle:Default:index }
register:
    path: /register
    defaults: { _controller: AppBundle:Register:register }
logout:
    path: /logout
lobby:
    path: /lobby
    defaults: { _controller: AppBundle:Default:lobby }
change_password:
    path: /change_password
    defaults: { _controller: AppBundle:Default:changePassword }
newproject:
    path: /newproject
    defaults : { _controller: AppBundle:Project:createNew }
unlockproject:
    path: /unlock/{proj}
    defaults: { _controller: AppBundle:Project:unlock }
lockproject:
    path: /lock/{proj}
    defaults: { _controller: AppBundle:Project:lock }
deleteproject:
    path: /delete/project/{projId}
    defaults: { _controller: AppBundle:Project:delete }
seeproject:
    path: /project/{proj}
    defaults: { _controller: AppBundle:Project:info }
seeprofile:
    path: /user/{user}
    defaults: { _controller: AppBundle:User:info }