app:
    resource: "@AppBundle/Controller/"
    type:     annotation
home:
    path: /home
    defaults: { _controller: AppBundle:Default:index }
register:
    path: /register
    defaults: { _controller: AppBundle:Register:register }
logout:
    path: /logout
lobby:
    path: /lobby
    defaults: { _controller: AppBundle:Default:lobby }
change_password:
    path: /change_password
    defaults: { _controller: AppBundle:Default:changePassword }
newproject:
    path: /newproject
    defaults : { _controller: AppBundle:Project:createNew }
unlockproject:
    path: /unlock/{proj}
    defaults: { _controller: AppBundle:Project:unlock }
lockproject:
    path: /lock/{proj}
    defaults: { _controller: AppBundle:Project:lock }
deleteproject:
    path: /delete/project/{projId}
    defaults: { _controller: AppBundle:Project:delete }
seeproject:
    path: /project/{projId}
    defaults: { _controller: AppBundle:Project:info }
seeprofile:
    path: /user/{user}
    defaults: { _controller: AppBundle:User:info }
add-meeting:
    path: /project/{projId}/add-meeting
    defaults: { _controller: AppBundle:Meeting:create }
add-role:
    path: /project/{projId}/add-role
    defaults: { _controller: AppBundle:Role:create }
add-agenda-item:
    path: /add-item/{agendaId}
    defaults: { _controller: AppBundle:ItemAgenda:create }
remove-role:
    path: /remove-role/{roleId}
    defaults: { _controller: AppBundle:Role:remove }
remove-meeting:
    path: /remove-meeting/{meetingId}
    defaults: { _controller: AppBundle:Meeting:remove }
see-meeting:
    path: /meeting/{meetingId}
    defaults: { _controller: AppBundle:Meeting:show }
save-answer:
    path: /save-answer/{answerId}
    defaults: { _controller: AppBundle:Meeting:saveAnswer }
save-agenda-items:
    path: /agenda/{agendaId}/save-items
    defaults: { _controller: AppBundle:Meeting:saveItems }
send-request:
    path: /agenda/{agendaId}/send-request
    defaults: { _controller: AppBundle:Agenda:sendRequest }
get-agenda-json:
    path: /agenda/{agendaId}/json
    defaults: { _controller: AppBundle:Agenda:getAgenda }
update-request:
    path: /update-request/{requestId}
    defaults: { _controller: AppBundle:UserRequest:updateRequest }
update-item:
    path: /update-item/{itemId}
    defaults: { _controller: AppBundle:ItemAgenda:update }
remove-item:
    path: /remove-item/{itemId}
    defaults: { _controller: AppBundle:ItemAgenda:remove }
my-projects:
    path: /my-projects
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    lobby/projectlist.html.twig
my-meetings:
    path: /my-meetings
    defaults:
        _controller: FrameworkBundle:Template:template
        template: lobby/meetinglist.html.twig
all-users-json:
    path: /all-users/json
    defaults: { _controller: AppBundle:User:getAll }
all-projects-json:
    path: /all-projects/json
    defaults: { _controller: AppBundle:Project:getAll }
all-projects:
    path: /all-projects
    defaults:
        _controller: FrameworkBundle:Template:template
        template: lobby/allprojects.html.twig
all-users:
    path: /all-users
    defaults:
        _controller: FrameworkBundle:Template:template
        template: lobby/allusers.html.twig
reset-password:
    path: /reset-password/{userId}
    defaults: { _controller: AppBundle:User:resetPassword }
get-project-json:
    path: project/{projId}/json
    defaults: { _controller: AppBundle:Project:getJson }
update-role:
    path: /update-role/{roleId}
    defaults: { _controller: AppBundle:Role:update }
update-meeting:
    path: /update-meeting/{meetingId}
    defaults: { _controller: AppBundle:Meeting:update }
see-meeting-minute:
    path: /meeting/{meetingId}/minute
    defaults: { _controller: AppBundle:Minute:index }
minute-json:
    path: /meeting/{meetingId}/minute/json
    defaults: { _controller: AppBundle:Minute:minuteJson }
edit-presence:
    path: /edit-presence/{presenceId}
    defaults: { _controller: AppBundle:Minute:editPresence }
post-comment:
    path: /meeting/{meetingId}/minute/post-comment
    defaults: { _controller: AppBundle:Minute:postComment }
see-minute-item:
    path: /minute-item/{itemId}/{json}
    defaults: { _controller: AppBundle:MinuteItem:index, json: false }
    requirements:
        json: (false|json)
add-minute-action:
    path: /minute-item/{itemId}/add-action
    defaults: { _controller: AppBundle:MinuteItem:addAction }
edit-minute-action:
    path: /minute-item/{itemId}/edit-action/{actionId}
    defaults: { _controller: AppBundle:MinuteItem:editAction }
submit-minute-action:
    path: /minute-item/{itemId}/submit-action/{actionId}
    defaults: { _controller: AppBundle:MinuteItem:submitAction }