# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
        
        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            logout:
                path: /logout
                target: /
            form_login:
                login_path: home
                check_path: home
                default_target_path: lobby
            # activate different ways to authenticate
            
    access_control:
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/newproject, roles: ROLE_ADMIN }
        - { path: ^/lock, roles: ROLE_ADMIN }
        - { path: ^/unlock, roles: ROLE_ADMIN }
        - { path: ^/all-users, roles: ROLE_ADMIN }
        - { path: ^/all-projects, roles: ROLE_ADMIN }
        - { path: ^/reset-password, roles: ROLE_ADMIN }
        - { path: ^/delete/project, roles: ROLE_ADMIN }
        - { path: ^/lobby, roles: ROLE_USER }
        - { path: ^/my-meetings, roles: ROLE_USER }
        - { path: ^/my-projects, roles: ROLE_USER }
